name: avurudu_nakath
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_timer_countdown: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sun.png
    - assets/sunFace.png

  fonts:
    - family: UNDisapamok
      fonts:
        - asset: assets/fonts/UN-Disapamok.ttf
    - family: UNIndeewaree
      fonts:
        - asset: assets/fonts/UN-Indeewaree.ttf
    - family: UNArundathee
      fonts:
        - asset: assets/fonts/UN-Arundathee.ttf
    - family: UNGurulugomi
      fonts:
        - asset: assets/fonts/UN-Gurulugomi.ttf
